version: '3'
services:

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped


networks:
  mysql:
    driver: bridge
volumes:
  mysql:
  workbench:
