services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: ${DATABASE_HOST}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql
    restart: unless-stopped

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - workbench:/config
    networks:
      - mysql
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped


networks:
#  postgres:
#    driver: bridge
  mysql:
    driver: bridge
volumes:
  mysql:
  workbench:

#  postgres:
#  pgadmin:
